[package]
name = "tuno-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
axum = "0.8.1"
rmpv = { version = "1.3.0", features = ["with-serde"] }
serde = { version = "1.0.218", features = ["derive"] }
socketioxide = "0.16.1"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
