[package]
name = "tuno-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
futures-util = "0.3.31"
native-tls = "0.2.14"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
toml = "0.8.20"
