// @generated by protobuf-ts 2.9.6 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "tuno.proto" (package "tuno", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Tuno } from "./tuno";
import type { StreamResponse } from "./tuno";
import type { StreamRequest } from "./tuno";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { EchoResponse } from "./tuno";
import type { EchoRequest } from "./tuno";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service tuno.Tuno
 */
export interface ITunoClient {
    /**
     * Echo request that returns the same message
     *
     * @generated from protobuf rpc: Echo(tuno.EchoRequest) returns (tuno.EchoResponse);
     */
    echo(input: EchoRequest, options?: RpcOptions): UnaryCall<EchoRequest, EchoResponse>;
    /**
     * Stream request that returns binary data
     *
     * @generated from protobuf rpc: Stream(tuno.StreamRequest) returns (tuno.StreamResponse);
     */
    stream(input: StreamRequest, options?: RpcOptions): UnaryCall<StreamRequest, StreamResponse>;
}
/**
 * @generated from protobuf service tuno.Tuno
 */
export class TunoClient implements ITunoClient, ServiceInfo {
    typeName = Tuno.typeName;
    methods = Tuno.methods;
    options = Tuno.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Echo request that returns the same message
     *
     * @generated from protobuf rpc: Echo(tuno.EchoRequest) returns (tuno.EchoResponse);
     */
    echo(input: EchoRequest, options?: RpcOptions): UnaryCall<EchoRequest, EchoResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EchoRequest, EchoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Stream request that returns binary data
     *
     * @generated from protobuf rpc: Stream(tuno.StreamRequest) returns (tuno.StreamResponse);
     */
    stream(input: StreamRequest, options?: RpcOptions): UnaryCall<StreamRequest, StreamResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamRequest, StreamResponse>("unary", this._transport, method, opt, input);
    }
}
