/**
 * @fileoverview gRPC-Web generated client stub for tuno
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: tuno.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.tuno = require('./tuno_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tuno.TunoClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tuno.TunoPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tuno.EchoRequest,
 *   !proto.tuno.EchoResponse>}
 */
const methodDescriptor_Tuno_Echo = new grpc.web.MethodDescriptor(
  '/tuno.Tuno/Echo',
  grpc.web.MethodType.UNARY,
  proto.tuno.EchoRequest,
  proto.tuno.EchoResponse,
  /**
   * @param {!proto.tuno.EchoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tuno.EchoResponse.deserializeBinary
);


/**
 * @param {!proto.tuno.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tuno.EchoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tuno.EchoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tuno.TunoClient.prototype.echo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tuno.Tuno/Echo',
      request,
      metadata || {},
      methodDescriptor_Tuno_Echo,
      callback);
};


/**
 * @param {!proto.tuno.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tuno.EchoResponse>}
 *     Promise that resolves to the response
 */
proto.tuno.TunoPromiseClient.prototype.echo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tuno.Tuno/Echo',
      request,
      metadata || {},
      methodDescriptor_Tuno_Echo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tuno.StreamRequest,
 *   !proto.tuno.StreamResponse>}
 */
const methodDescriptor_Tuno_Stream = new grpc.web.MethodDescriptor(
  '/tuno.Tuno/Stream',
  grpc.web.MethodType.UNARY,
  proto.tuno.StreamRequest,
  proto.tuno.StreamResponse,
  /**
   * @param {!proto.tuno.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tuno.StreamResponse.deserializeBinary
);


/**
 * @param {!proto.tuno.StreamRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tuno.StreamResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tuno.StreamResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tuno.TunoClient.prototype.stream =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tuno.Tuno/Stream',
      request,
      metadata || {},
      methodDescriptor_Tuno_Stream,
      callback);
};


/**
 * @param {!proto.tuno.StreamRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tuno.StreamResponse>}
 *     Promise that resolves to the response
 */
proto.tuno.TunoPromiseClient.prototype.stream =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tuno.Tuno/Stream',
      request,
      metadata || {},
      methodDescriptor_Tuno_Stream);
};


module.exports = proto.tuno;

