// @generated by protobuf-ts 2.9.6 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "tuno.proto" (package "tuno", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tuno.EchoRequest
 */
export interface EchoRequest {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
/**
 * @generated from protobuf message tuno.EchoResponse
 */
export interface EchoResponse {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
/**
 * @generated from protobuf message tuno.SongRequest
 */
export interface SongRequest {
    /**
     * @generated from protobuf field: string object_id = 1;
     */
    objectId: string;
}
/**
 * @generated from protobuf message tuno.SongStreamRequest
 */
export interface SongStreamRequest {
    /**
     * @generated from protobuf field: string object_id = 1;
     */
    objectId: string;
    /**
     * @generated from protobuf field: uint32 block_size = 2;
     */
    blockSize: number;
}
/**
 * @generated from protobuf message tuno.SongBytes
 */
export interface SongBytes {
    /**
     * @generated from protobuf field: bytes data = 1;
     */
    data: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class EchoRequest$Type extends MessageType<EchoRequest> {
    constructor() {
        super("tuno.EchoRequest", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message tuno.EchoRequest
 */
export const EchoRequest = new EchoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EchoResponse$Type extends MessageType<EchoResponse> {
    constructor() {
        super("tuno.EchoResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message tuno.EchoResponse
 */
export const EchoResponse = new EchoResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SongRequest$Type extends MessageType<SongRequest> {
    constructor() {
        super("tuno.SongRequest", [
            { no: 1, name: "object_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message tuno.SongRequest
 */
export const SongRequest = new SongRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SongStreamRequest$Type extends MessageType<SongStreamRequest> {
    constructor() {
        super("tuno.SongStreamRequest", [
            { no: 1, name: "object_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "block_size", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message tuno.SongStreamRequest
 */
export const SongStreamRequest = new SongStreamRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SongBytes$Type extends MessageType<SongBytes> {
    constructor() {
        super("tuno.SongBytes", [
            { no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message tuno.SongBytes
 */
export const SongBytes = new SongBytes$Type();
/**
 * @generated ServiceType for protobuf service tuno.Tuno
 */
export const Tuno = new ServiceType("tuno.Tuno", [
    { name: "Echo", options: {}, I: EchoRequest, O: EchoResponse },
    { name: "FetchSong", options: {}, I: SongRequest, O: SongBytes },
    { name: "StreamSong", serverStreaming: true, options: {}, I: SongStreamRequest, O: SongBytes }
]);
